### ISSUE TITLE
Improve docs

### ISSUE THREAD

**Issue by Mister-Hope** [gera2ld/npm2url#1]
The documentation about this package is pretty bad for users to understand.

```ts
import { urlBuilder } from "npm2url";

const url: string = urlBuilder.getFullUrl('npm2url');
const url: string = urlBuilder.getFullUrl('npm2url', 'jsdelivr');

// find the fastest provider
await urlBuilder.findFastestProvider();
const fastestUrl = urlBuilder.getFullUrl('npm2url');

// find the fastest provider temporarily
const fastest = await urlBuilder.getFastestProvider();
const fastestUrl = urlBuilder.getFullUrl('npm2url', fastest);
```

Users will be questioning:

1. what does `getFullUrl` do? Author should give examples about these results.

```ts
const url: string = urlBuilder.getFullUrl('npm2url');
const url: string = urlBuilder.getFullUrl('npm2url', 'jsdelivr');
```

Users are not expected to understand what they should fill in with the `'npm2url'` and what result does the pacakge return without reading code

2. Give a full provider list. The code does not show which key word it supports as provider:

Like the demo is using `jsdelivr`, uses must read through codes to get other keywords

```ts
const url: string = urlBuilder.getFullUrl('npm2url', 'jsdelivr');
```

**Comment by gera2ld** [comment]
I never expected someone else would look into this project.
You are right. Let me improve the documentation later.

**Comment by Mister-Hope** [comment]
![image](https://github.com/user-attachments/assets/9e466696-e561-42b7-8083-f09635aed0db)

Any update? I believe this is important as you already expose it in other projects
